version: '3.9'

services:
  app:
    build:
      context: app/.
      dockerfile: Dockerfile
    # command: ["sleep", "infinity"]
    container_name: ai-agent-server
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
