version: '3.9'

services:
  app:
    build:
      context: app/.
      dockerfile: Dockerfile
    # command: ["sleep", "infinity"]
    container_name: ai-agent-server
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    networks:
      - shared-net
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: server-gateway
    volumes:
      - ./gateway:/app
      - ./shared:/shared
    ports:
      - "8100:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DOPPLER_TOKEN: ${DOPPLER_TOKEN}
    networks:
      - shared-net

networks:
  shared-net:
    external: true
